# Generated by Django 3.0.8 on 2020-07-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='company_name',
            new_name='agency_name',
        ),
    ]
