# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20200726_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='date_updated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='date_created',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(default='unk@unk.com', max_length=150),
        ),
        migrations.AddField(
            model_name='agency',
            name='fax',
            field=models.CharField(default='925-222-9876', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
