# Generated by Django 3.0.8 on 2020-08-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20200829_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='fax',
            new_name='fax_number',
        ),
    ]
