# Generated by Django 3.0.8 on 2020-08-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20200801_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GL', 'General Liability'), ('WC', 'Workers Comp'), ('AU', 'Auto'), ('CR', 'Cargo'), ('UM', 'Umbrella')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pdf', models.FileField(blank=True, upload_to='pdfs/')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurance',
            },
        ),
    ]
