# Generated by Django 3.0.8 on 2020-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_number', models.CharField(blank=True, max_length=20)),
                ('equip_name', models.CharField(blank=True, max_length=50)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='users/')),
            ],
        ),
    ]
