# Generated by Django 3.0.8 on 2020-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20200711_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='equip_driver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='profile_image',
            field=models.ImageField(blank=True, default='equipment/default.jpg', null=True, upload_to='equipment/'),
        ),
    ]
