# Generated by Django 3.0.8 on 2020-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20200711_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
