# Generated by Django 3.0.8 on 2020-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20200711_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
