# Generated by Django 3.0.8 on 2020-07-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200725_1550'),
        ('vehicle', '0005_auto_20200714_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
            preserve_default=False,
        ),
    ]
