# Generated by Django 3.0.8 on 2020-07-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200725_1550'),
        ('vehicle', '0006_vehicle_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='employee',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='equip_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
