# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200801_1550'),
        ('vehicle', '0007_auto_20200725_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('P', 'Puller'), ('T', 'Trailer'), ('W', 'Water Truck'), ('Su', 'Super'), ('Sw', 'Sweeper')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length',
            field=models.CharField(default=45, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='kw', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='width',
            field=models.CharField(default=45, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='equip_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
