# Generated by Django 3.0.8 on 2020-08-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20200824_0055'),
        ('vehicle', '0008_auto_20200801_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_image',
            field=models.ManyToManyField(blank=True, to='image.Image'),
        ),
    ]
