# Generated by Django 3.0.8 on 2020-09-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehicle_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image_image',
        ),
    ]
