# Generated by Django 3.0.8 on 2020-08-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20200822_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
