# Generated by Django 3.0.8 on 2020-08-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20200824_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_image',
            field=models.FileField(blank=True, default='image/default.jpg', null=True, upload_to='image/'),
        ),
    ]
