# Generated by Django 3.0.8 on 2020-08-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20200826_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['equip_number'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_image',
            field=models.FileField(blank=True, default='image/default.jpg', null=True, upload_to='image/'),
        ),
    ]
