# Generated by Django 3.0.8 on 2020-08-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200801_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='com',
        ),
    ]
