# Generated by Django 3.0.8 on 2020-08-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200801_1827'),
        ('contact', '0007_remove_contact_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
