# Generated by Django 3.0.8 on 2020-08-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20200801_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='com',
        ),
    ]
