# Generated by Django 3.0.8 on 2020-08-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20200801_2131'),
        ('contact', '0010_auto_20200801_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
