# Generated by Django 3.0.8 on 2020-08-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20200801_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
