# Generated by Django 3.0.8 on 2020-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20200809_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
