# Generated by Django 3.0.8 on 2020-07-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('address1', models.CharField(blank=True, max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, choices=[('CA', 'California'), ('NV', 'Nevada')], max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=14)),
                ('fax_phone', models.CharField(blank=True, max_length=14)),
                ('type', models.CharField(blank=True, choices=[('C', 'C Corp'), ('S', 'S Corp'), ('L', 'LLC'), ('P', 'Partnership'), ('U', 'Unknown')], max_length=1, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='company/default.jpg', null=True, upload_to='company/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
