# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200726_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='date_updated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='date_created',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
