# Generated by Django 3.0.8 on 2020-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200801_1822'),
        ('company', '0004_auto_20200801_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='people',
            field=models.ManyToManyField(to='contact.Contact'),
        ),
    ]
