# Generated by Django 3.0.8 on 2020-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20200801_2131'),
        ('company', '0010_auto_20200801_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contacts',
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='contact.Contact'),
        ),
    ]
