# Generated by Django 3.0.8 on 2020-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200802_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('V', 'Vendor'), ('C', 'Customer')], max_length=1, null=True),
        ),
    ]
