#Generated by Django 3.0.8 on 2020-08-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20200809_0020'),
        ('company', '0012_company_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='contact.Contact'),
        ),
    ]
