# Generated by Django 3.0.8 on 2020-08-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20200801_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIR', 'DIR Number'), ('BL', 'Business License'), ('HP', 'Hire Package'), ('MS', 'Miscellaneous')], max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pdf', models.FileField(blank=True, upload_to='pdfs/')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
