# Generated by Django 3.0.8 on 2020-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20200801_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, upload_to='document/'),
        ),
    ]
