# Generated by Django 3.0.8 on 2020-08-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200809_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
