# Generated by Django 3.0.8 on 2020-08-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20200822_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
