# Generated by Django 3.0.8 on 2020-07-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address1', models.CharField(blank=True, max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('emergency_phone', models.CharField(blank=True, max_length=12)),
                ('emergency_contact', models.CharField(blank=True, max_length=12)),
                ('dob', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('cdl', models.CharField(blank=True, max_length=12)),
                ('cdl_endorsement', models.CharField(blank=True, max_length=12)),
                ('notes', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='equipment/default.jpg', null=True, upload_to='equipment/')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
