# Generated by Django 3.0.8 on 2020-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200722_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, choices=[('CA', 'CALIFORNIA'), ('NV', 'NEVADA')], max_length=2, null=True),
        ),
    ]
