# Generated by Django 3.0.8 on 2020-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200725_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cdl_endorsement',
        ),
        migrations.AddField(
            model_name='employee',
            name='cdl_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, choices=[('CA', 'California'), ('NV', 'Nevada')], max_length=2, null=True),
        ),
    ]
