# Generated by Django 3.0.8 on 2020-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200725_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='med_expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
