# Generated by Django 3.0.8 on 2020-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cdl_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
