# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name')},
        ),
    ]
