# Generated by Django 3.0.8 on 2020-07-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_number',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
