# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0003_auto_20200801_1550'),
        ('vehicle', '0008_auto_20200801_1550'),
        ('company', '0003_auto_20200801_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_cn', models.CharField(max_length=150, unique=True, verbose_name='Permit number')),
                ('agency_type', models.CharField(blank=True, choices=[('CI', 'City'), ('CO', 'County'), ('ST', 'State')], max_length=2, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('permit_class', models.CharField(max_length=40)),
                ('loaded_height', models.CharField(max_length=150)),
                ('loaded_width', models.CharField(max_length=150)),
                ('pdf', models.FileField(blank=True, upload_to='pdfs/')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.Agency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
            },
        ),
    ]
