# Generated by Django 3.0.8 on 2020-08-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20200801_1550'),
        ('agency', '0003_auto_20200801_1550'),
        ('company', '0011_auto_20200802_1945'),
        ('permit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permits',
            new_name='Permit',
        ),
    ]
